// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP59A_Bp2zz2Hp2Hf6EPrBGF3puoBKovc',
    appId: '1:49616297399:android:466d76c4b7231b390e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    storageBucket: 'deneme2-bc96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNFyAxaGJH0mHl-Mot3PYe5c462D_vLc',
    appId: '1:49616297399:ios:b5209f425d87e9530e5c32',
    messagingSenderId: '49616297399',
    projectId: 'deneme2-bc96d',
    storageBucket: 'deneme2-bc96d.appspot.com',
    iosBundleId: 'com.utkuyilmaz.ngyApp',
  );
}
